[package]
name = "advent"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"

[[bin]]
path = "day_1/main.rs"
name = "day_1"

[[bin]]
path = "day_2/main.rs"
name = "day_2"

[[bin]]
path = "day_3/main.rs"
name = "day_3"
